In [11]:
#1
import numpy as np

ARR1 = np.random.rand(3, 4)
print(ARR1)

print(np.mean(ARR1, axis=1))
print(np.std(ARR1, axis=1))
print(np.var(ARR1, axis=1))

[[0.19972081 0.5218507  0.56711151 0.88210919]
 [0.88692172 0.80433791 0.24142022 0.68434934]
 [0.27562368 0.59772183 0.22007487 0.46825728]]
[0.54269805 0.6542573  0.39041942]
[0.2417974  0.24899644 0.15102016]
[0.05846598 0.06199923 0.02280709]


In [3]:
m = int(input())
n = int(input())

arr = np.random.randint(1, 100, (m, n))

print(arr)
print(arr.shape)
print(type(arr))
print(arr.dtype)

reshaped = arr.reshape(n, m)
print(reshaped)

[[31 84  9 60]
 [71 80 73 68]
 [10 31 86 36]]
(3, 4)
<class 'numpy.ndarray'>
int64
[[31 84  9]
 [60 71 80]
 [73 68 10]
 [31 86 36]]


In [4]:
arr = np.array([0, 1, np.nan, 5, 0])

print(np.where(arr == 0)[0])
print(np.where((arr != 0) & ~np.isnan(arr))[0])
print(np.where(np.isnan(arr))[0])

[0 4]
[1 3]
[2]


In [5]:
A1 = np.random.rand(5)
A2 = np.random.rand(5)
A3 = np.random.rand(5)

A4 = A3 - A2
A5 = 2 * A1

print(np.cov(A1, A4))
print(np.corrcoef(A1, A5))

[[ 0.06572855 -0.05340392]
 [-0.05340392  0.32953281]]
[[1. 1.]
 [1. 1.]]


In [6]:
A1 = np.random.randint(1, 10, 10)
A2 = np.random.randint(1, 10, 10)

print(np.sum(A1[:5] + A2[:5]))
print(np.prod(A1[5:] * A2[5:]))

58
3048192


In [7]:
arr = np.random.rand(10, 10)

print(arr.nbytes)

800


In [8]:
m = int(input())
n = int(input())

arr = np.random.randint(10, 100, (m, n))
print(arr)

arr[[0, 1]] = arr[[1, 0]]

arr2 = arr.copy()
arr2[:, 1] = arr2[::-1, 1]

print(arr2)

[[18 27 44 13]
 [55 88 73 10]
 [59 82 91 77]]
[[55 82 73 10]
 [18 27 44 13]
 [59 88 91 77]]


In [ ]:
#2
import pandas as pd

s = pd.Series([5, 2, 9, 1, 7], index=['e','b','a','d','c'])

print(s.sort_index())
print(s.sort_values())

a    9
b    2
c    7
d    1
e    5
dtype: int64
d    1
b    2
e    5
c    7
a    9
dtype: int64


In [12]:
s = pd.Series([10, 20, 20, 30, 10])

print(s.rank(method='first'))
print(s.rank(method='max'))

0    1.0
1    3.0
2    4.0
3    5.0
4    2.0
dtype: float64
0    2.0
1    4.0
2    4.0
3    5.0
4    2.0
dtype: float64


In [13]:
s = pd.Series([5, 2, 9, 1, 7], index=['e','b','a','d','c'])

print(s.idxmin())
print(s.idxmax())

d
a


In [16]:
#3
df = pd.DataFrame(np.random.randn(50, 3), columns=['A','B','C'])

for _ in range(int(0.1 * df.size)):
    i = np.random.randint(0, 50)
    j = np.random.randint(0, 3)
    df.iat[i, j] = np.nan

In [ ]:
print(df.isnull().sum())

A    5
B    4
C    5
dtype: int64


In [18]:
df = df.dropna(axis=1, thresh=45)

In [20]:
row = df.sum(axis=1).idxmax()
df = df.drop(row)

In [21]:
df = df.drop_duplicates(subset=df.columns[0])

In [22]:
print(df[df.columns[0]].corr(df[df.columns[1]]))
print(df[df.columns[1]].cov(df[df.columns[2]]))

-0.15938376025584572
-0.22233053665110233


In [23]:
df['B_bins'] = pd.cut(df[df.columns[1]], bins=5)
print(df.head())

          A         B         C             B_bins
0  1.303911  0.333009       NaN   (-0.0194, 0.808]
1 -1.192593  0.314299 -2.195842   (-0.0194, 0.808]
2 -0.168686 -0.219222 -0.652388  (-0.847, -0.0194]
3  1.046406 -0.855077 -0.523553   (-1.679, -0.847]
4  0.303423  1.086881  0.515791     (0.808, 1.636]
